"""Pure, one-recording analysis implementations."""

from .api import (
    AnalysisConfigurationError,
    AnalysisExecutionContext,
    AnalysisInputError,
    QualityPsdAnalyzer,
    QualityPsdConfig,
    quality_psd_algorithm_ref,
    quality_psd_config_ref,
)
from .codec import (
    FEATURE_SET_FORMAT_ID,
    FEATURE_SET_MEDIA_TYPE,
    MAX_FEATURE_SET_BYTES,
    MalformedFeatureSetError,
    decode_feature_set,
    encode_feature_set,
)
from .decisions import MethodFiring, ThresholdRule, apply_threshold_rule
from .detector_suite import (
    DetectorSuiteConfig,
    IndependentDetectorSuite,
    detector_suite_algorithm_ref,
    detector_suite_config_ref,
)
from .persistence import (
    DurableFeatureSetRepository,
    FeatureSetIntegrityError,
    FeatureSetNotFoundError,
)
from .starlink import (
    KnownCodePilotSearchConfigV0_1,
    KnownCodePilotSearchV0_1,
    KnownCodePilotTemplatePairV0_1,
    evaluate_pilot_candidate_v0_1,
    known_code_pilot_algorithm_ref_v0_1,
    known_code_pilot_config_ref_v0_1,
    template_samples_digest,
)
from .starlink_calibration import (
    approved_calibration_v0_1,
    evaluate_calibration_cell_v0_1,
    minimum_holdout_searches,
    one_sided_wilson_upper_bound,
    plan_starlink_calibration_cell_v0_1,
)
from .starlink_detector_suite import (
    StarlinkDetectorSuiteConfigV0_2,
    StarlinkDetectorSuiteV0_2,
    StarlinkInjectionCaseV0_2,
    StarlinkInjectionTrialResultV0_2,
    StarlinkPssSssTemplateV0_2,
    StarlinkRadioCandidateObservationV0_2,
    build_multi_radio_candidate_evidence_v0_2,
    run_starlink_injection_cases_v0_2,
    starlink_detector_suite_algorithm_ref_v0_2,
    starlink_detector_suite_config_ref_v0_2,
    synthesize_starlink_injection_v0_2,
)
from .starlink_events import cluster_starlink_beacon_events_v0_1
from .starlink_suite_codec import (
    MAX_STARLINK_SUITE_BUNDLE_BYTES,
    STARLINK_SUITE_FORMAT_ID,
    STARLINK_SUITE_MEDIA_TYPE,
    decode_starlink_suite_bundle,
    encode_starlink_suite_bundle,
)
from .starlink_suite_recording import ExactStarlinkDetectorSuiteRecordingAnalyzerV0_2
from .starlink_templates import (
    qin_edge_pilot_artifacts_v0_1,
    qin_edge_pilot_frame_v1,
    qin_edge_pilot_states_v1,
    qin_edge_pilot_template_pair_v0_1,
    qin_source_citation_ref_v1,
)
from .waterfall import (
    BoundedWaterfallAnalyzerV0_1,
    WaterfallConfigV0_1,
    waterfall_algorithm_ref_v0_1,
    waterfall_config_ref_v0_1,
)
from .waterfall_codec import (
    MAX_WATERFALL_BUNDLE_BYTES,
    WATERFALL_FORMAT_ID,
    WATERFALL_MEDIA_TYPE,
    MalformedWaterfallError,
    decode_waterfall_bundle,
    encode_waterfall_bundle,
)
from .waterfall_persistence import (
    DurableWaterfallRepositoryV0_1,
    WaterfallIntegrityError,
    WaterfallNotFoundError,
)

__all__ = [
    "FEATURE_SET_FORMAT_ID",
    "FEATURE_SET_MEDIA_TYPE",
    "MAX_FEATURE_SET_BYTES",
    "MAX_STARLINK_SUITE_BUNDLE_BYTES",
    "MAX_WATERFALL_BUNDLE_BYTES",
    "STARLINK_SUITE_FORMAT_ID",
    "STARLINK_SUITE_MEDIA_TYPE",
    "WATERFALL_FORMAT_ID",
    "WATERFALL_MEDIA_TYPE",
    "AnalysisConfigurationError",
    "AnalysisExecutionContext",
    "AnalysisInputError",
    "BoundedWaterfallAnalyzerV0_1",
    "DetectorSuiteConfig",
    "DurableFeatureSetRepository",
    "DurableWaterfallRepositoryV0_1",
    "ExactStarlinkDetectorSuiteRecordingAnalyzerV0_2",
    "FeatureSetIntegrityError",
    "FeatureSetNotFoundError",
    "IndependentDetectorSuite",
    "KnownCodePilotSearchConfigV0_1",
    "KnownCodePilotSearchV0_1",
    "KnownCodePilotTemplatePairV0_1",
    "MalformedFeatureSetError",
    "MalformedWaterfallError",
    "MethodFiring",
    "QualityPsdAnalyzer",
    "QualityPsdConfig",
    "StarlinkDetectorSuiteConfigV0_2",
    "StarlinkDetectorSuiteV0_2",
    "StarlinkInjectionCaseV0_2",
    "StarlinkInjectionTrialResultV0_2",
    "StarlinkPssSssTemplateV0_2",
    "StarlinkRadioCandidateObservationV0_2",
    "ThresholdRule",
    "WaterfallConfigV0_1",
    "WaterfallIntegrityError",
    "WaterfallNotFoundError",
    "apply_threshold_rule",
    "approved_calibration_v0_1",
    "build_multi_radio_candidate_evidence_v0_2",
    "cluster_starlink_beacon_events_v0_1",
    "decode_feature_set",
    "decode_starlink_suite_bundle",
    "decode_waterfall_bundle",
    "detector_suite_algorithm_ref",
    "detector_suite_config_ref",
    "encode_feature_set",
    "encode_starlink_suite_bundle",
    "encode_waterfall_bundle",
    "evaluate_calibration_cell_v0_1",
    "evaluate_pilot_candidate_v0_1",
    "known_code_pilot_algorithm_ref_v0_1",
    "known_code_pilot_config_ref_v0_1",
    "minimum_holdout_searches",
    "one_sided_wilson_upper_bound",
    "plan_starlink_calibration_cell_v0_1",
    "qin_edge_pilot_artifacts_v0_1",
    "qin_edge_pilot_frame_v1",
    "qin_edge_pilot_states_v1",
    "qin_edge_pilot_template_pair_v0_1",
    "qin_source_citation_ref_v1",
    "quality_psd_algorithm_ref",
    "quality_psd_config_ref",
    "run_starlink_injection_cases_v0_2",
    "starlink_detector_suite_algorithm_ref_v0_2",
    "starlink_detector_suite_config_ref_v0_2",
    "synthesize_starlink_injection_v0_2",
    "template_samples_digest",
    "waterfall_algorithm_ref_v0_1",
    "waterfall_config_ref_v0_1",
]
