"""Independent process composition surfaces."""

from .analysis import (
    AnalysisCycle,
    AnalysisJobProcessor,
    FencedAnalysisCycle,
    build_analysis_service,
)
from .bootstrap import (
    AdapterBuildContext,
    AdapterFactory,
    AdapterManifest,
    BootstrapError,
    Capability,
    DeploymentPlugin,
    Process,
    ProcessBuilder,
    SecretProvider,
    assemble_service,
)
from .capture import CaptureCycle, build_capture_service
from .config import (
    AnalysisServiceConfig,
    CaptureServiceConfig,
    ConfigurationError,
    DashboardServiceConfig,
    RuntimeConfig,
    SecretRef,
    ServiceConfig,
    load_service_config,
    parse_service_config,
)
from .dashboard import ReadOnlyDashboardServer, build_dashboard_service
from .lifecycle import (
    DiagnosticEvent,
    DiagnosticSink,
    HealthSnapshot,
    JsonLineDiagnosticSink,
    ServiceLifecycleError,
    ServiceLoop,
    ServiceState,
)
from .recording_analysis import (
    RECORDING_ANALYSIS_JOB_SCHEMA,
    FencedRecordingAnalysisWorker,
    PreparedRecordingAnalysis,
    RecordingAnalysisJobError,
    RecordingAnalysisJobPreparer,
    decode_recording_analysis_payload,
    recording_analysis_payload,
)

__all__ = [
    "RECORDING_ANALYSIS_JOB_SCHEMA",
    "AdapterBuildContext",
    "AdapterFactory",
    "AdapterManifest",
    "AnalysisCycle",
    "AnalysisJobProcessor",
    "AnalysisServiceConfig",
    "BootstrapError",
    "Capability",
    "CaptureCycle",
    "CaptureServiceConfig",
    "ConfigurationError",
    "DashboardServiceConfig",
    "DeploymentPlugin",
    "DiagnosticEvent",
    "DiagnosticSink",
    "FencedAnalysisCycle",
    "FencedRecordingAnalysisWorker",
    "HealthSnapshot",
    "JsonLineDiagnosticSink",
    "PreparedRecordingAnalysis",
    "Process",
    "ProcessBuilder",
    "ReadOnlyDashboardServer",
    "RecordingAnalysisJobError",
    "RecordingAnalysisJobPreparer",
    "RuntimeConfig",
    "SecretProvider",
    "SecretRef",
    "ServiceConfig",
    "ServiceLifecycleError",
    "ServiceLoop",
    "ServiceState",
    "assemble_service",
    "build_analysis_service",
    "build_capture_service",
    "build_dashboard_service",
    "decode_recording_analysis_payload",
    "load_service_config",
    "parse_service_config",
    "recording_analysis_payload",
]
